# This file is auto-generated by Godot — do not edit.
# It exists to indicate that Floor_0.tscn, Mrak.tscn, etc.
# need to be built in the Godot Editor using the provided scripts.
#
# SETUP INSTRUCTIONS:
# 1. Install Godot 4.3 from https://godotengine.org/download
# 2. Open Godot → Import Project → select this folder
# 3. Create the following scenes manually in the editor:
#
# ═══════════════════════════════════════
# SCENE: scenes/world/Floor_0.tscn
# ═══════════════════════════════════════
# Node2D (Floor_0)
# ├── TileMapLayer (Ground) — layer: 0 (walls/floors)
# ├── TileMapLayer (Decoration) — layer: 1 (pipes, cracks)
# ├── ParallaxBackground
# │   ├── ParallaxLayer (BG Far)  motion_scale: (0.1, 0.05)
# │   ├── ParallaxLayer (BG Mid)  motion_scale: (0.3, 0.1)
# │   └── ParallaxLayer (BG Near) motion_scale: (0.6, 0.2)
# ├── MrakSpawnPoint (Marker2D)
# ├── Mrak.tscn [instance]
# ├── SchizophrenicUI.tscn [instance]
# └── WorldEnvironment
#
# ═══════════════════════════════════════
# SCENE: scenes/entities/Mrak.tscn
# ═══════════════════════════════════════
# CharacterBody2D (Mrak) — script: scripts/entities/Mrak.gd
#   Groups: ["mrak"]
# ├── AnimatedSprite2D
# │   └── SpriteFrames: assets/sprites/mrak/mrak_sheet.png
# │       Animations: idle, crawl, crawl_low, crouch_idle, fall, climb
# ├── CollisionShape2D (standing — CapsuleShape2D h:48 w:16)
# ├── CollisionShape2D (CrouchShape — RectangleShape2D h:24 w:16) disabled=true
# ├── PointLight2D (HeatCore) — texture_scale:2.0 color:#00FFCC energy:0.8
# ├── Area2D (SoundEmissionArea)
# │   └── CollisionShape2D (SoundShape — CircleShape2D r:190)
# ├── Area2D (InteractArea)
# │   └── CollisionShape2D (CircleShape2D r:32)
# ├── MrakBody.gd node [Node2D]
# │   ├── PointLight2D (PinGlow) — on chest bone
# │   ├── Sprite2D (ThermalCore) — heat core visual
# │   ├── Sprite2D (NecrosisOverlay) — crack projection
# │   ├── Label (NecrosisLabel) — "70%" projected text
# │   ├── Node2D (SpineShards) — 5 small Sprite2D children
# │   └── Timer (FlickerTimer) one_shot:false wait_time:0.18
# ├── AudioStreamPlayer (HeartbeatPlayer) — bus:Heartbeat
# ├── AudioStreamPlayer (FootstepPlayer) — bus:SFX
# └── CanvasLayer (UILayer) layer:5
#     └── ColorRect (BlinkOverlay) — fullscreen color:#000000 alpha:0
#
# ═══════════════════════════════════════
# SCENE: scenes/ui/SchizophrenicUI.tscn
# ═══════════════════════════════════════
# CanvasLayer — script: scripts/systems/SchizophrenicUI.gd layer:10
# ├── Control (FirewallLayer) — anchors: top-left, size: 400x200
# │   └── RichTextLabel (FirewallLog) bbcode_enabled:true
# ├── Node2D (MemoryLeakLayer) — floating labels injected here
# ├── ColorRect (VignetteOverlay) — fullscreen ShaderMaterial: vignette_dynamic.gdshader
# ├── ColorRect (CRTOverlay) — fullscreen ShaderMaterial: crt_scanline.gdshader alpha:0.6
# ├── ColorRect (GlitchOverlay) — fullscreen ShaderMaterial: glitch_displacement.gdshader
# └── Timer (ChaosShakeTimer) one_shot:false
#
# ═══════════════════════════════════════
# AUDIO BUSES (Project Settings → Audio)
# ═══════════════════════════════════════
# Master
# ├── SFX  (muted during Nhắm Mắt)
# ├── Music
# ├── Voice
# ├── Heartbeat (always audible)
# └── Spatial (enemy positional audio — always audible)
